all : test.c background_anon1.c  background_anon2.c background_file1.c background_file2.c 
	gcc -o test test.c
	gcc -o background_anon1 background_anon1.c
	gcc -o background_anon2 background_anon2.c
	gcc -o background_file1 background_file1.c
	gcc -o background_file2 background_file2.c
	gcc -o background_static background_static.c

